### ISSUE TITLE
Avoid mutating a prop directly in Vue2.0

### ISSUE THREAD

**Issue by karonl** [myronliu347/vue-popup-mixin#1]
In the Vue2.0, I use this vue-popup in my project and get this error message when I close the popup.  
```
 Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "show" 
(found in component <dialogc> at dialogc.vue);

```
I find that the error caused by "this.show = false" , We can solve through "$emit('close')" and set show false in parent component.

**Comment by myronliu347** [comment]
Only use in 1.0 

2.0  you can look  https://github.com/museui/muse-ui/tree/master/src/internal/popup
